services:
  editor:
    image: ghcr.io/shopwarelabs/devcontainer/base-slim:8.2@sha256:1c67f419cd08700a8bf8d58439fc06a7087a7879489d0b20f676f7899b554aeb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: chainguard/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bloktra
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - "8080:8080"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 32M
      
volumes:
  db-data:
