services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
